// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package utils

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCd93bc43DecodeMysqlSlowGoUtilsUser(in *jlexer.Lexer, out *User_obj) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "value":
			out.Value = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCd93bc43EncodeMysqlSlowGoUtilsUser(out *jwriter.Writer, in User_obj) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix[1:])
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v User_obj) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsUser(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v User_obj) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsUser(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *User_obj) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsUser(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *User_obj) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsUser(l, v)
}
func easyjsonCd93bc43DecodeMysqlSlowGoUtilsSLOWLOG(in *jlexer.Lexer, out *SLOWLOG_JSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "classes":
			if in.IsNull() {
				in.Skip()
				out.Classes = nil
			} else {
				in.Delim('[')
				if out.Classes == nil {
					if !in.IsDelim(']') {
						out.Classes = make([]Class_arr, 0, 0)
					} else {
						out.Classes = []Class_arr{}
					}
				} else {
					out.Classes = (out.Classes)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Class_arr
					(v1).UnmarshalEasyJSON(in)
					out.Classes = append(out.Classes, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "global":
			(out.Global).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCd93bc43EncodeMysqlSlowGoUtilsSLOWLOG(out *jwriter.Writer, in SLOWLOG_JSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"classes\":"
		out.RawString(prefix[1:])
		if in.Classes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Classes {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"global\":"
		out.RawString(prefix)
		(in.Global).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SLOWLOG_JSON) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsSLOWLOG(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SLOWLOG_JSON) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsSLOWLOG(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SLOWLOG_JSON) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsSLOWLOG(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SLOWLOG_JSON) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsSLOWLOG(l, v)
}
func easyjsonCd93bc43DecodeMysqlSlowGoUtilsQueryTime(in *jlexer.Lexer, out *Query_time_obj) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "avg":
			out.Avg = string(in.String())
		case "max":
			out.Max = string(in.String())
		case "min":
			out.Min = string(in.String())
		case "pct_95":
			out.Pct_95 = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCd93bc43EncodeMysqlSlowGoUtilsQueryTime(out *jwriter.Writer, in Query_time_obj) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"avg\":"
		out.RawString(prefix[1:])
		out.String(string(in.Avg))
	}
	{
		const prefix string = ",\"max\":"
		out.RawString(prefix)
		out.String(string(in.Max))
	}
	{
		const prefix string = ",\"min\":"
		out.RawString(prefix)
		out.String(string(in.Min))
	}
	{
		const prefix string = ",\"pct_95\":"
		out.RawString(prefix)
		out.String(string(in.Pct_95))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Query_time_obj) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsQueryTime(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Query_time_obj) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsQueryTime(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Query_time_obj) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsQueryTime(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Query_time_obj) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsQueryTime(l, v)
}
func easyjsonCd93bc43DecodeMysqlSlowGoUtilsMetric(in *jlexer.Lexer, out *Metric_obj) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "db":
			(out.Dbs).UnmarshalEasyJSON(in)
		case "host":
			(out.Hosts).UnmarshalEasyJSON(in)
		case "user":
			(out.Users).UnmarshalEasyJSON(in)
		case "Query_time":
			(out.Query_time).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCd93bc43EncodeMysqlSlowGoUtilsMetric(out *jwriter.Writer, in Metric_obj) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"db\":"
		out.RawString(prefix[1:])
		(in.Dbs).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"host\":"
		out.RawString(prefix)
		(in.Hosts).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix)
		(in.Users).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"Query_time\":"
		out.RawString(prefix)
		(in.Query_time).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Metric_obj) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsMetric(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Metric_obj) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsMetric(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Metric_obj) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsMetric(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Metric_obj) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsMetric(l, v)
}
func easyjsonCd93bc43DecodeMysqlSlowGoUtilsHost(in *jlexer.Lexer, out *Host_obj) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "value":
			out.Value = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCd93bc43EncodeMysqlSlowGoUtilsHost(out *jwriter.Writer, in Host_obj) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix[1:])
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Host_obj) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsHost(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Host_obj) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsHost(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Host_obj) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsHost(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Host_obj) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsHost(l, v)
}
func easyjsonCd93bc43DecodeMysqlSlowGoUtilsGlobal(in *jlexer.Lexer, out *Global_obj) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "query_count":
			out.Query_count = int(in.Int())
		case "unique_query_count":
			out.Unique_query_count = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCd93bc43EncodeMysqlSlowGoUtilsGlobal(out *jwriter.Writer, in Global_obj) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"query_count\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Query_count))
	}
	{
		const prefix string = ",\"unique_query_count\":"
		out.RawString(prefix)
		out.Int(int(in.Unique_query_count))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Global_obj) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsGlobal(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Global_obj) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsGlobal(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Global_obj) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsGlobal(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Global_obj) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsGlobal(l, v)
}
func easyjsonCd93bc43DecodeMysqlSlowGoUtilsExample(in *jlexer.Lexer, out *Example_obj) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Query_time":
			out.Query_time = string(in.String())
		case "query":
			out.Query = string(in.String())
		case "ts":
			out.Ts = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCd93bc43EncodeMysqlSlowGoUtilsExample(out *jwriter.Writer, in Example_obj) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Query_time\":"
		out.RawString(prefix[1:])
		out.String(string(in.Query_time))
	}
	{
		const prefix string = ",\"query\":"
		out.RawString(prefix)
		out.String(string(in.Query))
	}
	{
		const prefix string = ",\"ts\":"
		out.RawString(prefix)
		out.String(string(in.Ts))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Example_obj) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsExample(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Example_obj) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsExample(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Example_obj) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsExample(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Example_obj) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsExample(l, v)
}
func easyjsonCd93bc43DecodeMysqlSlowGoUtilsDb(in *jlexer.Lexer, out *Db_obj) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "value":
			out.Value = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCd93bc43EncodeMysqlSlowGoUtilsDb(out *jwriter.Writer, in Db_obj) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix[1:])
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Db_obj) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsDb(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Db_obj) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsDb(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Db_obj) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsDb(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Db_obj) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsDb(l, v)
}
func easyjsonCd93bc43DecodeMysqlSlowGoUtilsClass(in *jlexer.Lexer, out *Class_arr) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "attribute":
			out.Attribute = string(in.String())
		case "checksum":
			out.Checksum = string(in.String())
		case "example":
			(out.Examples).UnmarshalEasyJSON(in)
		case "query_count":
			out.Query_count = int(in.Int())
		case "ts_max":
			out.Ts_max = string(in.String())
		case "ts_min":
			out.Ts_min = string(in.String())
		case "metrics":
			(out.Metrics).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCd93bc43EncodeMysqlSlowGoUtilsClass(out *jwriter.Writer, in Class_arr) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"attribute\":"
		out.RawString(prefix[1:])
		out.String(string(in.Attribute))
	}
	{
		const prefix string = ",\"checksum\":"
		out.RawString(prefix)
		out.String(string(in.Checksum))
	}
	{
		const prefix string = ",\"example\":"
		out.RawString(prefix)
		(in.Examples).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"query_count\":"
		out.RawString(prefix)
		out.Int(int(in.Query_count))
	}
	{
		const prefix string = ",\"ts_max\":"
		out.RawString(prefix)
		out.String(string(in.Ts_max))
	}
	{
		const prefix string = ",\"ts_min\":"
		out.RawString(prefix)
		out.String(string(in.Ts_min))
	}
	{
		const prefix string = ",\"metrics\":"
		out.RawString(prefix)
		(in.Metrics).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Class_arr) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsClass(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Class_arr) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCd93bc43EncodeMysqlSlowGoUtilsClass(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Class_arr) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsClass(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Class_arr) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCd93bc43DecodeMysqlSlowGoUtilsClass(l, v)
}
